// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYYSvx5CHOjdinfH9blpUX3rTbb87OL2E',
    appId: '1:745797471292:web:6dad385de82333b5408739',
    messagingSenderId: '745797471292',
    projectId: 'mynotes-flutter-edlavio',
    authDomain: 'mynotes-flutter-edlavio.firebaseapp.com',
    storageBucket: 'mynotes-flutter-edlavio.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDkhuxDMyj52gN1MWw8u1fgRp_N73Yzdc',
    appId: '1:745797471292:android:1af7fd933d33cbb6408739',
    messagingSenderId: '745797471292',
    projectId: 'mynotes-flutter-edlavio',
    storageBucket: 'mynotes-flutter-edlavio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoXDbCURenCrZjaqJnTMu9XyH2R-SwSG8',
    appId: '1:745797471292:ios:3c78c9f6418090d8408739',
    messagingSenderId: '745797471292',
    projectId: 'mynotes-flutter-edlavio',
    storageBucket: 'mynotes-flutter-edlavio.firebasestorage.app',
    iosBundleId: 'me.edlavio.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoXDbCURenCrZjaqJnTMu9XyH2R-SwSG8',
    appId: '1:745797471292:ios:3c78c9f6418090d8408739',
    messagingSenderId: '745797471292',
    projectId: 'mynotes-flutter-edlavio',
    storageBucket: 'mynotes-flutter-edlavio.firebasestorage.app',
    iosBundleId: 'me.edlavio.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYYSvx5CHOjdinfH9blpUX3rTbb87OL2E',
    appId: '1:745797471292:web:ba16837ba7a36ba0408739',
    messagingSenderId: '745797471292',
    projectId: 'mynotes-flutter-edlavio',
    authDomain: 'mynotes-flutter-edlavio.firebaseapp.com',
    storageBucket: 'mynotes-flutter-edlavio.firebasestorage.app',
  );
}
